name: Download Instagram Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12 PM UTC

jobs:
  download_instagram_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Instaloader
        run: pip install instaloader

      - name: Restore Instagram Session
        run: |
          mkdir -p ~/.config/instaloader/
          echo "${{ secrets.INSTALOADER_SESSION }}" | base64 --decode > ~/.config/instaloader/session-kylewhirl

      - name: Run Instagram Image Downloader
        run: python download_instagram.py

      - name: Rename images to 1.jpg, 2.jpg, and 3.jpg
        run: |
          cd instagram-images
          ls -1t | head -n 3 | awk '{print "mv "$0" "NR".jpg"}' | bash
          cd ..

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add instagram-images/
          git diff --staged --quiet || (git commit -m "Update Instagram images" && git push)
